core/urls.py
"""
     Urls
"""
from django.urls import path
from .views import accept_terms, core, email, bank, faq, site

# pylint: disable=invalid-name
app_name = 'core'

urlpatterns = [
    path('inicio/', core.StartView.as_view(), name='start_page'),

    path('usuarios/administradores/',
         core.AdminListView.as_view(), name='admin_list'),
    path('usuarios/administradores/editar/<int:pk>/',
         core.AdminUpdateView.as_view(), name='admin_update'),
    path('usuarios/administradores/alterar-senha/<int:pk>/',
         core.ChangeAdminPasswordView.as_view(), name='change_admin_password'),

    path('usuarios/ativacao-senha/', core.UserListView.as_view(), name='user_list'),
    path('usuarios/ativacao-senha/editar/<int:pk>/',
         core.UserUpdateView.as_view(), name='user_update'),
    path('usuarios/ativacao-senha/alterar-senha/<int:pk>/',
         core.ChangeUserPasswordView.as_view(), name='change_user_password'),

    path('usuarios/clientes/', core.ClientListView.as_view(), name='client_list'),
    path('usuarios/clientes/novo/',
         core.ClientCreateView.as_view(), name='client_create'),
    path('usuarios/clientes/editar/<int:pk>/',
         core.ClientUpdateView.as_view(), name='client_update'),

    path('usuarios/mensagens/', email.EmailListView.as_view(), name='email_list'),
    path('usuarios/mensagens/novo/',
         email.EmailCreateView.as_view(), name='email_create'),
    path('usuarios/mensagens/detalhe/<int:pk>/',
         email.EmailUpdateView.as_view(), name='email_detail'),
    path('usuarios/mensagens/log/<int:pk>/',
         email.EmailLogView.as_view(), name='email_log'),

    path('usuarios/dados-bancarios/',
         bank.BankAccountListView.as_view(), name='bank_account_list'),
    path('usuarios/dados-bancarios/novo/',
         bank.BankAccountCreateView.as_view(), name='bank_account_create'),
    path('usuarios/dados-bancarios/editar/<int:pk>/',
         bank.BankAccountUpdateView.as_view(), name='bank_account_update'),


    path('contratos/termos-de-aceite/', accept_terms.AcceptanceTermListView.as_view(),
         name='acceptance_term_list'),
    path('contratos/termos-de-aceite/novo/',
         accept_terms.AcceptanceTermCreateView.as_view(), name='acceptance_term_create'),
    path('contratos/termos-de-aceite/editar/<int:pk>/',
         accept_terms.AcceptanceTermUpdateView.as_view(), name='acceptance_term_update'),

    path('api/', core.ApiUserView.as_view(), name='api_page'),

    path('tarefas/', core.WorkflowTaskListView.as_view(), name='task_list'),

    path('configuracoes/empresa/',
         core.CompanyListView.as_view(), name='company_list'),
    path('configuracoes/empresa/novo/',
         core.CompanyCreateView.as_view(), name='company_create'),
    path('configuracoes/empresa/editar/<int:pk>/',
         core.CompanyUpdateView.as_view(), name='company_update'),

    path('configurações/faq/',
         faq.FAQConfigListView.as_view(), name='faq_config_list'),
    path('configurações/faq/novo/',
         faq.FAQConfigCreateView.as_view(), name='faq_config_create'),
    path('configurações/faq/editar/<int:pk>/',
         faq.FAQConfigUpdateView.as_view(), name='faq_config_update'),

    path('configurações/faq/questoes/',
         faq.FAQListView.as_view(), name='faq_list'),
    path('configurações/faq/questoes/novo/',
         faq.FAQCreateView.as_view(), name='faq_create'),
    path('configurações/faq/questoes/editar/<int:pk>/',
         faq.FAQUpdateView.as_view(), name='faq_update'),

    path('configuracoes/pagina-inicial/',
         site.StartPageListView.as_view(), name='start_page_list'),
    path('configuracoes/pagina-inicial/novo/',
         site.StartPageCreateView.as_view(), name='start_page_create'),
    path('configuracoes/pagina-inicial/editar/<int:pk>/',
         site.StartPageUpdateView.as_view(), name='start_page_update'),

]

products/urls.py
"""
     Urls
"""
from django.urls import path

from .views import agreements, products

# pylint: disable=invalid-name
app_name = 'products'

urlpatterns = [

    path('contratos/produtos/', agreements.AgreementListView.as_view(),
         name='agreement_list'),
    path('contratos/produtos/novo/',
         agreements.AgreementCreateView.as_view(), name='agreement_create'),
    path('contratos/produtos/editar/<int:pk>/',
         agreements.AgreementUpdateView.as_view(), name='agreement_update'),
    path('contratos/produtos/dados/',
         agreements.AgreementJsonView.as_view(), name='agreement_data'),
    path('contrato/preview/<int:pk>/',
         agreements.UserAgreementPreview.as_view(), name='agreement_preview'),
    path('contrato-cliente/<int:pk>/',
         agreements.UserAgreementPrintView.as_view(), name='agreement_detail'),

    path('produtos/', products.ProductListView.as_view(), name='product_list'),
    path('produtos/novo/',
         products.ProductCreateView.as_view(), name='product_create'),
    path('produtos/editar/<int:pk>/',
         products.ProductUpdateView.as_view(), name='product_update'),
    path('produto-info/', products.ProductJsonData.as_view(), name='product_info_js'),
    path('produtos-contratados/', products.ProductPurchaseListView.as_view(),
         name='product_purchase_list'),

    path('produtos/categorias/',
         products.ProductCategoryListView.as_view(), name='category_list'),
    path('produtos/categorias/novo/',
         products.ProductCategoryCreateView.as_view(), name='category_create'),
    path('produtos/categorias/editar/<int:pk>/',
         products.ProductCategoryUpdateView.as_view(), name='category_update'),

    path('produtos/categorias/documentos/',
         products.CategoryDocumentListView.as_view(), name='category_document_list'),
    path('produtos/categorias/documento/novo/',
         products.CategoryDocumentCreateView.as_view(), name='category_document_create'),
    path('produtos/categorias/documentos/editar/<int:pk>/',
         products.CategoryDocumentUpdateView.as_view(), name='category_document_update'),

    path('dashboads/', products.DashboardListView.as_view(),
         name='dashboard_list'),
    path('dashboads/novo/',
         products.DashboardCreateView.as_view(), name='dashboard_create'),
    path('dashboads/editar/<int:pk>/',
         products.DashboardUpdateView.as_view(), name='dashboard_update'),

    path('perfis/', products.ProfileProductListView.as_view(),
         name='profile_product_list'),
    path('perfis/novo/', products.ProfileProductCreate.as_view(),
         name='profile_product_create'),
    path('perfis/<int:pk>/', products.ProfileProductUpdate.as_view(),
         name='profile_product_update'),

]

speedseven/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django_select2.views import AutoResponseView

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from clients.views import clients
from core.views.core import TinyMceUploadView, TinyMceDocView
from investment.views.operations import ReceiptsView


admin.site.site_url = '/adm/inicio/'


urlpatterns = [
    path('adm/', include('core.urls')),
    path('adm/', include('emailtemplates.urls')),
    path('adm/', include('products.urls')),
    path('adm/', include('investorprofile.urls')),
    path('adm/', include('investment.urls_adm')),
    path('adm/api/', include('accounts.urls_api')),
    path('adm/usuarios/convites/', include('accounts.urls_invitation')),

    path('admin/', admin.site.urls),
    path('contas/', include('accounts.urls_account')),
    path('cliente/', include('clients.urls')),
    path('', include('website.urls')),
    path('media/private/uploads/<path:file_name>/',
         clients.ClientDocsView.as_view(), name='document_download'),

    path('media/private/receipts/<path:file_name>/',
         ReceiptsView.as_view(), name='receipts_download'),

    path('api/', include('core.urls_api')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('api/v1/', include('clients.api.urls')),

    path("select2/", include(([path("fields/auto.json", login_required(
        AutoResponseView.as_view()), name="auto-json")], 'django_select2'))),

    path(settings.TINYMCE_URL, TinyMceUploadView.as_view(),
         name='upload_tinymce_image'),

    path(settings.TINYMCE_URL+'<str:file_name>',
         TinyMceDocView.as_view(), name='tinymce_doc_image'),

]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL + 'public',
                          document_root=settings.MEDIA_ROOT / 'public')

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.LandingView.as_view(), name='landing_page'),
    path('produtos/', views.ProductsView.as_view(), name='product_page'),
    path('produtos/categorias/documentos/<int:pk>/',
         views.CategoryDocumentDetailView.as_view(), name='category_document_detail'),
    path('termos/<slug:type>/',
         views.AcceptanceTermPrintView.as_view(), name='term_page'),

]

website/models.py
from django.db import models

# Create your models here.

core/forms/faq.py
"""
FAQ form
"""

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row
from django import forms
from core import models


class FAQForm(forms.ModelForm):
    """
    Acceptance term form
    """

    class Meta:
        """
        Meta class
        """
        model = models.FAQ
        fields = '__all__'
        widgets = {
            'faq_config': forms.widgets.CheckboxSelectMultiple
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if not self.instance.pk:
            #pylint: disable=no-member
            try:
                last_question_order = models.FAQ.objects.latest('order')
                self.initial['order'] = last_question_order.order + 1
            except models.FAQ.DoesNotExist:
                self.initial['order'] = 1

        self.helper = FormHelper()

        self.helper.layout = Layout(
            Row('question'),
            Row('answer'),
            Row('order'),
            Row('faq_config'),
        )

core/views/faq.py
"""
Faq views
"""

from django.urls import reverse_lazy
from common.views import mixins, generic
from core import tables, models
from core.forms.faq import FAQForm


class FAQConfigListView(mixins.AdminMixin,
                        mixins.ListViewMixin):
    """
    FAQ config list view
    """
    model = models.FAQConfig
    template_name = 'common/list.html'
    title = 'Páginas de ajuda'
    table_class = tables.FAQConfigTable

    controls = [
        {'link': {'text': 'Novo', 'url': 'core:faq_config_create'}},
    ]


class FAQConfigCreateView(mixins.AdminMixin,
                          generic.CreateView):
    """
    FAQ config create view
    """
    model = models.FAQConfig
    fields = '__all__'
    template_name = 'common/form.html'
    title = 'Página de ajuda'
    success_url = reverse_lazy('core:faq_config_list')
    cancel_url = success_url


class FAQConfigUpdateView(mixins.AdminMixin,
                          generic.UpdateView):
    """
    FAQ config update view
    """
    model = models.FAQConfig
    fields = '__all__'
    template_name = 'common/form.html'
    title = 'Página de ajuda'
    success_url = reverse_lazy('core:faq_config_list')
    cancel_url = success_url


class FAQListView(mixins.AdminMixin,
                  mixins.ListViewMixin):
    """
    FAQ list view
    """
    model = models.FAQ
    template_name = 'common/list.html'
    title = 'Questões frequentes'

    table_class = tables.FAQTable

    controls = [
        {'link': {'text': 'Novo', 'url': 'core:faq_create'}},
    ]


class FAQCreateView(mixins.AdminMixin,
                    generic.CreateView):
    """
    FAQ create view
    """
    model = models.FAQ
    form_class = FAQForm
    template_name = 'common/form.html'
    title = 'Nova questão'
    success_url = reverse_lazy('core:faq_list')
    cancel_url = success_url


class FAQUpdateView(mixins.AdminMixin,
                    generic.UpdateView):
    """
    FAQ update view
    """
    model = models.FAQ
    form_class = FAQForm
    template_name = 'common/form.html'
    title = 'Questão'
    success_url = reverse_lazy('core:faq_list')
    cancel_url = success_url
    enable_delete = True
    confirm_operation = 'delete'

products/views/agreements.py
"""
    Agreement views
"""
from http import HTTPStatus

from django.http import Http404, JsonResponse
from django.urls import reverse_lazy
from django.views import View

from accounts.auth import mixins as auth_mixins
from common.views import generic, mixins
from products import models as product_models

from .. import tables
from ..forms.products import AgreementForm
from ..models import AgreementTemplate


class AgreementListView(mixins.AdminMixin,
                        mixins.ListViewMixin):
    """
    Agreements list
    """
    model = AgreementTemplate
    table_class = tables.AgreementTable
    template_name = 'common/list.html'
    title = 'Modelos de contrato'
    controls = [
        {'link': {'text': 'Novo', 'url': 'products:agreement_create'}},
    ]


class AgreementCreateView(mixins.AdminMixin,
                          generic.CreateView):
    """
    Create agreement
    """
    model = AgreementTemplate
    form_class = AgreementForm
    template_name = 'common/form.html'
    title = 'Modelo de contrato'
    success_url = reverse_lazy('products:agreement_list')
    cancel_url = success_url


class AgreementUpdateView(mixins.AdminMixin,
                          generic.UpdateView):
    """
    Update agreement
    """
    model = AgreementTemplate
    form_class = AgreementForm
    template_name = 'common/form.html'
    title = 'Modelo de contrato'
    success_url = reverse_lazy('products:agreement_list')
    cancel_url = success_url


class AgreementJsonView(auth_mixins.LoginRequiredMixin, View):
    """
    Product agreeemnt text
    """

    # pylint: disable=unused-argument
    def get(self, request, *args, **kwargs):
        """
        Product agreement text
        """
        product_id = self.request.GET.get('product_id')

        if product_id:
            # pylint: disable=no-member
            agreement_template = AgreementTemplate.objects.filter(
                product__pk=product_id,
                type=self.request.user.client.type).last()

            agreement_renderer = agreement_template.product.application. \
                application_class.get_agreement_class()

            if agreement_template:
                text = agreement_renderer.render(
                    self.request.user, agreement_template.text, extra_args=self.request.GET)
                return JsonResponse(
                    {
                        "text": text,
                        'agreement_term': agreement_template.term_str,
                        'product': {
                            'display_text': agreement_template.product.display_text

                        }

                    }, status=HTTPStatus.OK)

        return JsonResponse(
            {"error": 'Contrato indisponível no momento'},
            status=HTTPStatus.OK
        )


class UserAgreementPrintView(mixins.AdminMixin,
                             generic.PrintView):
    """
    Detail and print view for acceptance terms
    """

    model = product_models.ProductPurchase
    template_name = 'common/print.html'
    title = 'Contrato do cliente'

    def get_content(self):
        product_purchase_pk = self.kwargs.get('pk', None)
        if product_purchase_pk:
            try:
                # pylint: disable=no-member
                user_agreement = self.model.objects.get(
                    pk=product_purchase_pk,
                )
                return {
                    'text': user_agreement.agreement
                }
                # pylint: disable=no-member
            except self.model.DoesNotExist as exc:
                raise Http404(exc) from exc
        return dict()


class UserAgreementPreview(mixins.AdminMixin,
                           generic.PrintView):
    """
    Detail and print view for acceptance terms
    """

    model = product_models.AgreementTemplate
    template_name = 'common/print.html'
    title = 'Exemplo de contrato'

    def get_content(self):
        agreement_pk = self.kwargs.get('pk', None)
        if agreement_pk:
            try:
                # pylint: disable=no-member
                agreement = self.model.objects.get(
                    pk=agreement_pk,
                )

                agreement_renderer = agreement.product.application.application_class.get_agreement_class()

                text = '<h5>Exemplo de contrato para visualização</h5><br>'+agreement.text
                return {
                    'text': agreement_renderer.render(
                        user=None, agreement_text=text, preview=True)
                }
                # pylint: disable=no-member
            except self.model.DoesNotExist as exc:
                raise Http404(exc) from exc
        return dict()

products/views/dashboards.py
"""
Dashboard JSON view
"""

from charts.views import ChartJsonView
from accounts.auth import mixins as auth_mixin

from .. import dashboards as d


class ProductsDashboardJson(auth_mixin.LoginRequiredMixin, ChartJsonView):
    """
    Dashboars charts data in JSON format
    """

    #pylint: disable=unused-argument
    def get_dashboard(self, request, *args, **kwargs):
        """
        Dashboard data
        """
        return d.ProductsDashboard

website/templates/website/about_us.html
{% comment %}
    The about_us text is a html text from tinymce. The tags strong and span
    in the text has its colors not affected by div id_about_us_text style
    This style below force color matching
{% endcomment %}

<style>
    #id_about_us_text strong, span {
        color: {{company.about_us_colors.color}};
    }
</style>

<div id="id_about_us_text" style="background-color: {{company.about_us_colors.background_color}}; color: {{company.about_us_colors.color}}">
    <div class="row p-0 m-0">
        <div class="col p-4 m-4">
            {{company.about_us|safe}}
        </div>
        {% if company.abt_us_signup_btn %}
        <div class="text-center mb-4 p-4">
            <a href="/contas/signup/" class='btn btn-success rounded-pill px-4 fs-5 '> {{company.abt_us_signup_btn}} </a>
        </div>
        {% endif %}
    </div>
</div>

website/templates/website/banner.html
{% load static %}

<div class="row p-0 m-0">
    <div class="col p-0 m-0">
        <img src="{% static 'website/hawk.jpg' %}" style="max-width: 100%; min-width: 100%">
    </div>
</div>

website/templates/website/category_docs.html
{% extends 'website/page.html' %}

{% block content %}
<div class="container-fluid mt-2 text-success noprint ">
    {% block page_title %}
    <div class="h2 text-secondary pt-4 text-center">{{title}}</div>
    {% endblock %}
</div>
<div class="container-fluid m-0 p-0">
    {% block page_boby %}
    <div class="container noprint pb-4">
        <div class="d-flex flex-column justify-content-center bg-white" style="padding: 5rem 5rem;">
            {{content.text|safe}}
        </div>
    </div>
    <div class="print" style="display: none">
        <div class="d-flex flex-column justify-content-center" style="padding: 1rem 2rem;">
            {{content.text|safe}}
        </div>
    </div>
    {% endblock %}
</div>
{% endblock %}

website/templates/website/footer.html
{% load static %}


{% if not company.fix_disclaimer_end %}
<div class="d-flex fixed-bottom justify-content-center m-0 p-0" style="background-color: rgba(173, 173, 173, 0.4)"
    onmouseover="this.style.background='rgba(173, 173, 173, 1)';"
    onmouseout="this.style.background='rgba(173, 173, 173, 0.4)';">
    <div class="text-center w-100">
        <p class="m-0 p-2 text-black" style="font-size: 0.85rem;">{{company.disclaimer|safe}}</p>
    </div>
</div>
{% endif %}


<div class="row pt-4 mt-4 pb-4 px-0 mx-0 bg-white">
    <div class="col-12">
        <div class="d-flex justify-content-center">
            <div class="row p-0 m-0" style="max-width: 85%">

                <div class="col-md-4 pb-4 px-2 d-flex justify-content-md-start justify-content-center">
                    <div>
                        {% if company.logo %}
                        <div class="text-center mb-2">
                            <img src="{{ company.logo.url }}" width="45px">
                        </div>
                        {% endif %}
                        <p class="fw-bold"> SIGA NOSSAS REDES </p>
                        <div class="d-flex justify-content-around" style="font-size: 1.9rem;">
                            {% if company.facebook_link %}
                            <a href="{{company.facebook_url}}" class="text-decoration-none text-dark"><i class="bi bi-facebook"></i></a>
                            {% endif %}

                            {% if company.linkedin_link %}
                            <a href="{{company.linkedin_url}}" class="text-decoration-none text-dark"><i class="bi bi-linkedin"></i></a>
                            {% endif %}

                            {% if company.instagram_link %}
                            <a href="{{company.instagram_url}}" class="text-decoration-none text-dark"><i class="bi bi-instagram"></i></a>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="col-md-4 pb-4 px-2 d-flex justify-content-md-center justify-content-center">
                    <div>
                        <div class="fw-bold"> PRECISA DE AJUDA </div>
                        <p class="text-primary"><a href="mailto:{{company.contact_email}}">{{company.contact_email}}</a>
                        </p>
                        <div class="fw-bold"> TERMOS </div>
                        <div><a href="{% url 'website:term_page' 'termo-de-uso' %}" class="text-secondary text-decoration-none">Termos de uso</a></div>
                        <div><a href="{% url 'website:term_page' 'politica-de-privacidade' %}" class="text-secondary text-decoration-none">Política de privacidade</a></div>
                    </div>
                </div>

                <div class="col-md-4 d-flex  px-2 justify-content-md-end justify-content-center">
                    <div>
                        <div class="d-none d-md-block">
                            <div class="fw-bold"> FALE COM A GENTE </div>
                            <div>Atendimento</div>
                            {% if company.support_email %}
                            <p class="text-primary">
                                <a href="mailto:{{company.support_email}}">{{company.support_email}}</a>
                            </p>
                            {% endif %}
                            <div>Contato</div>
                            {% if company.support_phone %}
                            <div>{{company.support_phone}}</div>
                            {% endif %}
                            <p class="pt-2" style="font-size: .8em; text-align:justify; max-width: 200px">
                                <strong> Não ligamos para você por esse telefone</strong>, também não solicitamos dados
                                pessoais, senha de conta e código de transação por telefone. Estes números são somente
                                para você fazer ligações para {{request.site.name}}.
                            </p>
                        </div>

                        <div class="d-block d-md-none">
                            <div class="d-flex justify-content-center">
                                <div class="pb-4">
                                    <div class="fw-bold"> FALE COM A GENTE </div>
                                    <div>Atendimento</div>
                                    {% if company.support_email %}
                                    <p class="text-primary">
                                        <a href="mailto:{{company.support_email}}">{{company.support_email}}</a>
                                    </p>
                                    {% endif %}
                                    <div>Contato</div>
                                    {% if company.support_phone %}
                                    <div>{{company.support_phone}}</div>
                                    {% endif %}
                                </div>
                            </div>
                            <p class="pt-2 " style="font-size: .8em; text-align:justify;">
                                <strong> Não ligamos para você por esse telefone</strong>, também não solicitamos dados
                                pessoais, senha de conta e código de transação por telefone. Estes números são somente
                                para você fazer ligações para {{request.site.name}}.
                            </p>
                        </div>
                    </div>
                </div>

                {% if company.fix_disclaimer_end %}
                <div class="d-flex bg-white justify-content-center m-0 p-0">
                    <div class="text-center w-100">
                        <p class="m-0 p-0 text-secondary" style="font-size: 1em;">{{company.disclaimer|safe}}</p>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

website/templates/website/form.html
{% extends 'common/form.html' %}

{% block menu %}
    {% include 'website/menu.html' %}
{% endblock %}

website/templates/website/home.html
{% extends 'website/page.html' %}
{% load static %}


{% block body %}

<div class="container-fluid m-0 p-0">

    {% include 'website/menu.html' %}
    {% include 'website/banner.html' %}

    {% if company.about_us %}
    {% include 'website/about_us.html' %}
    {% endif %}

    <div class="row m-0 p-0 bg-light">
        <a href="{% url 'website:product_page' %}#id_produtos" class="col-12 text-center text-decoration-none"
            style="padding-top: 50px; padding-bottom: 50px;"><span class="h1 text-secondary"> Conheça nossos produtos
            </span></a>
    </div>

    {% for category, products in categories.items %}
    <div class="row m-0 p-0 {%cycle 'bg-white' 'bg-light' %}">
        <div class="row m-0 pt-4">
            <div class="h1 py-4 text-success text-center">{% if category.show_title %}{{category.title}}{% endif %}
            </div>
            {% for product in products %}
            <div class="col-lg-4 col-sm-12 mt-2 mt-sm-0 mb-4">
                <div class="card shadow" style="max-height: 480px; min-height: 480px;">
                    <div class="card-header fw-bold fs-3 rounded"> {{product.display_text}} </div>
                    <div class="card-body overflow-auto p-2">
                        <div> {{product.briefing|safe}}</div>
                    </div>
                    {%if product.application_info %}
                    <div class="card-body p-2 pb-0 d-flex">
                        <div class="align-self-end flex-fill pb-2">{{product.application_info|safe}}</div>
                    </div>
                    {% endif %}
                    <div class="card-footer bg-transparent m-0 p-0 ps-2 pt-2">
                        <a href="{% url 'website:product_page' %}#product_{{product.pk}}"
                            class="text-success text-decoration-none">
                            Saiba mais
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="d-flex px-4 flex-wrap py-4 justify-content-center">
            {% for document in category.categorydocument_set.all %}
            <a href="{% url 'website:category_document_detail' document.pk %}"
                class="mx-4 text-decoration-none text-secondary">{{document.display_text}} </a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}

    <div class="row m-0 p-0 pt-4 bg-black">
        <div class="col mt-2">
            <div class="d-flex flex-row justify-content-center" style="padding-top: 150px; padding-bottom: 150px;">
                <i class="bi bi-shield-check text-light h1 me-4 pt-2" style="font-size: 6rem;"></i>
                <div>
                    <p class="text-success my-0 py-0 display-5">Mais segurança </p>
                    <p class="text-success my-0 py-0 display-5">para suas transações</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row m-0 p-0 my-4 py-4">
        <div class="col mt-2">
            <p class="text-success my-0 py-0 h1 text-center">Comece a investir</p>
            <p class="my-0 py-0 h4 text-center mt-4">Gerencie seus próprios investimentos</p>
            <div class="row mt-4 pt-4">
                <div class="col-4 mt-2 text-center">
                    <div class="m-auto rounded-circle" style="width: 90px; height: 90px">
                        <img src="{% static 'website/wallet.png' %}" width="100%">
                    </div>
                    <p class="text-success my-0 py-0 h2 text-center mt-4">Passo 1 </p>
                    <p class="text-secondary my-0 py-0 h4 text-center mt-4"> Abra sua conta</p>
                </div>
                <div class="col-4 mt-2 text-center">
                    <div class="m-auto rounded-circle" style="width: 90px; height: 90px">
                        <img src="{% static 'website/doc.png' %}" width="100%">

                    </div>
                    <p class="text-success my-0 py-0 h2 text-center mt-4">Passo 2 </p>
                    <p class="text-secondary my-0 py-0 h4 text-center mt-4"> Prencha seu cadastro</p>
                </div>
                <div class="col-4 mt-2 text-center">
                    <div class="m-auto rounded-circle" style="width: 90px; height: 90px">
                        <img src="{% static 'website/scalable.png' %}" width="100%">
                    </div>
                    <p class="text-success my-0 py-0 h2 text-center mt-4">Passo 3 </p>
                    <p class="text-secondary my-0 py-0 h4 text-center mt-4"> Contrate um produto <br> e comece a
                        investir</p>
                </div>
            </div>
            <br>
            {% if config.ACCOUNT_ENABLE_SIGNUP %}
            <div class="row mt-4">
                <div class="col mt-2 text-center">
                    <a href="{% url 'account_signup' %}"
                        class="bg-success text-black p-3 rounded-pill h4 text-decoration-none"> Abra sua conta</a>
                </div>
            </div>
            {% endif %}
            <br>
            <br>
        </div>
    </div>

    {% if faq %}
    {% include 'website/faq.html' %}
    {% endif %}

    {% include 'website/footer.html' %}

</div>
{% endblock %}

website/templates/website/page.html
{% extends 'common/page.html' %}

{% block theme_script %}
<script>
    const body = document.getElementsByTagName("body")[0];
    body.classList.add('light');
</script>
{% endblock %}

{% block body %}
{% endblock %}