clients/urls.py
"""
     Urls
"""
from django.urls import path
from products.views import dashboards as core_dash_views

from .views import clients, dashboards, operations

# pylint: disable=invalid-name
app_name = 'clients'

urlpatterns = [
    path('inicio/', clients.StartView.as_view(), name='start_page'),

    path('cadastro/editar/',
         clients.ClientUpdateView.as_view(), name='client_update'),
    path('cadastro/termos-de-aceite/',
         clients.UserAcceptanceTermCreateView.as_view(), name='acceptance_term_create'),

    path('cadastro/perfil-de-investidor/',
         clients.InvestorProfileTestDetailView.as_view(), name='investor_profile_test_detail'),
    path('cadastro/perfil-de-investidor/novo/',
         clients.InvestorProfileTestCreateView.as_view(), name='investor_profile_test_create'),
    path('cadastro/perfil-de-investidor/editar/',
         clients.InvestorProfileTestUpdateView.as_view(), name='investor_profile_test_update'),

    path('cadastro/dados-bancarios/',
         clients.BankAccountListView.as_view(), name='bank_account_list'),
    path('cadastro/dados-bancarios/novo/',
         clients.BankAccountCreateView.as_view(), name='bank_account_create'),
    path('cadastro/dados-bancarios/editar/<int:pk>/',
         clients.BankAccountUpdateView.as_view(), name='bank_account_update'),

    path('produtos/', clients.ProductsView.as_view(), name='products_page'),
    path('produtos/contratar/<int:pk>',
         clients.ProductsPurchaseView.as_view(), name='products_purchase_page'),

    path('produtos/categorias/documentos/<int:pk>/',
         clients.CategoryDocumentDetailView.as_view(), name='category_document_detail'),


    path('broker/', clients.BrokerView.as_view(), name='broker_page'),

    path('consultas/extratos/', clients.ApplicationOpUserListView.as_view(),
         name='operationsstatement_page'),
    path('consultas/relatorio/', clients.ReportView.as_view(), name='report_page'),
    path('consultas/invetimentos/', clients.ProductPurcahseListView.as_view(),
         name='products_purchase_list'),
    path('consultas/invetimentos/editar/<int:pk>/',
         clients.ProductPurchaseUpdateView.as_view(), name='products_purchase_update'),
    path('consultas/contrato/<int:pk>/',
         clients.UserAgreementPrintView.as_view(), name='agreement_detail'),
    path('consultas/termos-de-aceite/',
         clients.UserAcceptanceTermListView.as_view(), name='acceptance_term_list'),
    path('consultas/termos-de-aceite/<int:pk>/',
         clients.UserAcceptanceTermPrintView.as_view(), name='acceptance_term_detail'),

    path('dashboard-data/', dashboards.ClientDashboardJson.as_view(),
         name='dashboard_client_data'),
    path('dashboard-products/', core_dash_views.ProductsDashboardJson.as_view(),
         name='dashboard_client_products_data'),

    path('trasferencias/aporte/<int:pk>/',
         operations.ClientDepositView.as_view(), name='deposit_create'),
    path('trasferencias/resgate/<int:pk>/',
         operations.ClientWithdrawView.as_view(), name='withdraw_create'),
    path('transferencias/',
         operations.MoneyTransferListView.as_view(), name='moneytransfer_list'),

    path('ajuda/', clients.HelpView.as_view(), name='help_page'),

]

core/urls.py
"""
     Urls
"""
from django.urls import path
from .views import accept_terms, core, email, bank, faq, site

# pylint: disable=invalid-name
app_name = 'core'

urlpatterns = [
    path('inicio/', core.StartView.as_view(), name='start_page'),

    path('usuarios/administradores/',
         core.AdminListView.as_view(), name='admin_list'),
    path('usuarios/administradores/editar/<int:pk>/',
         core.AdminUpdateView.as_view(), name='admin_update'),
    path('usuarios/administradores/alterar-senha/<int:pk>/',
         core.ChangeAdminPasswordView.as_view(), name='change_admin_password'),

    path('usuarios/ativacao-senha/', core.UserListView.as_view(), name='user_list'),
    path('usuarios/ativacao-senha/editar/<int:pk>/',
         core.UserUpdateView.as_view(), name='user_update'),
    path('usuarios/ativacao-senha/alterar-senha/<int:pk>/',
         core.ChangeUserPasswordView.as_view(), name='change_user_password'),

    path('usuarios/clientes/', core.ClientListView.as_view(), name='client_list'),
    path('usuarios/clientes/novo/',
         core.ClientCreateView.as_view(), name='client_create'),
    path('usuarios/clientes/editar/<int:pk>/',
         core.ClientUpdateView.as_view(), name='client_update'),

    path('usuarios/mensagens/', email.EmailListView.as_view(), name='email_list'),
    path('usuarios/mensagens/novo/',
         email.EmailCreateView.as_view(), name='email_create'),
    path('usuarios/mensagens/detalhe/<int:pk>/',
         email.EmailUpdateView.as_view(), name='email_detail'),
    path('usuarios/mensagens/log/<int:pk>/',
         email.EmailLogView.as_view(), name='email_log'),

    path('usuarios/dados-bancarios/',
         bank.BankAccountListView.as_view(), name='bank_account_list'),
    path('usuarios/dados-bancarios/novo/',
         bank.BankAccountCreateView.as_view(), name='bank_account_create'),
    path('usuarios/dados-bancarios/editar/<int:pk>/',
         bank.BankAccountUpdateView.as_view(), name='bank_account_update'),


    path('contratos/termos-de-aceite/', accept_terms.AcceptanceTermListView.as_view(),
         name='acceptance_term_list'),
    path('contratos/termos-de-aceite/novo/',
         accept_terms.AcceptanceTermCreateView.as_view(), name='acceptance_term_create'),
    path('contratos/termos-de-aceite/editar/<int:pk>/',
         accept_terms.AcceptanceTermUpdateView.as_view(), name='acceptance_term_update'),

    path('api/', core.ApiUserView.as_view(), name='api_page'),

    path('tarefas/', core.WorkflowTaskListView.as_view(), name='task_list'),

    path('configuracoes/empresa/',
         core.CompanyListView.as_view(), name='company_list'),
    path('configuracoes/empresa/novo/',
         core.CompanyCreateView.as_view(), name='company_create'),
    path('configuracoes/empresa/editar/<int:pk>/',
         core.CompanyUpdateView.as_view(), name='company_update'),

    path('configurações/faq/',
         faq.FAQConfigListView.as_view(), name='faq_config_list'),
    path('configurações/faq/novo/',
         faq.FAQConfigCreateView.as_view(), name='faq_config_create'),
    path('configurações/faq/editar/<int:pk>/',
         faq.FAQConfigUpdateView.as_view(), name='faq_config_update'),

    path('configurações/faq/questoes/',
         faq.FAQListView.as_view(), name='faq_list'),
    path('configurações/faq/questoes/novo/',
         faq.FAQCreateView.as_view(), name='faq_create'),
    path('configurações/faq/questoes/editar/<int:pk>/',
         faq.FAQUpdateView.as_view(), name='faq_update'),

    path('configuracoes/pagina-inicial/',
         site.StartPageListView.as_view(), name='start_page_list'),
    path('configuracoes/pagina-inicial/novo/',
         site.StartPageCreateView.as_view(), name='start_page_create'),
    path('configuracoes/pagina-inicial/editar/<int:pk>/',
         site.StartPageUpdateView.as_view(), name='start_page_update'),

]

products/urls.py
"""
     Urls
"""
from django.urls import path

from .views import agreements, products

# pylint: disable=invalid-name
app_name = 'products'

urlpatterns = [

    path('contratos/produtos/', agreements.AgreementListView.as_view(),
         name='agreement_list'),
    path('contratos/produtos/novo/',
         agreements.AgreementCreateView.as_view(), name='agreement_create'),
    path('contratos/produtos/editar/<int:pk>/',
         agreements.AgreementUpdateView.as_view(), name='agreement_update'),
    path('contratos/produtos/dados/',
         agreements.AgreementJsonView.as_view(), name='agreement_data'),
    path('contrato/preview/<int:pk>/',
         agreements.UserAgreementPreview.as_view(), name='agreement_preview'),
    path('contrato-cliente/<int:pk>/',
         agreements.UserAgreementPrintView.as_view(), name='agreement_detail'),

    path('produtos/', products.ProductListView.as_view(), name='product_list'),
    path('produtos/novo/',
         products.ProductCreateView.as_view(), name='product_create'),
    path('produtos/editar/<int:pk>/',
         products.ProductUpdateView.as_view(), name='product_update'),
    path('produto-info/', products.ProductJsonData.as_view(), name='product_info_js'),
    path('produtos-contratados/', products.ProductPurchaseListView.as_view(),
         name='product_purchase_list'),

    path('produtos/categorias/',
         products.ProductCategoryListView.as_view(), name='category_list'),
    path('produtos/categorias/novo/',
         products.ProductCategoryCreateView.as_view(), name='category_create'),
    path('produtos/categorias/editar/<int:pk>/',
         products.ProductCategoryUpdateView.as_view(), name='category_update'),

    path('produtos/categorias/documentos/',
         products.CategoryDocumentListView.as_view(), name='category_document_list'),
    path('produtos/categorias/documento/novo/',
         products.CategoryDocumentCreateView.as_view(), name='category_document_create'),
    path('produtos/categorias/documentos/editar/<int:pk>/',
         products.CategoryDocumentUpdateView.as_view(), name='category_document_update'),

    path('dashboads/', products.DashboardListView.as_view(),
         name='dashboard_list'),
    path('dashboads/novo/',
         products.DashboardCreateView.as_view(), name='dashboard_create'),
    path('dashboads/editar/<int:pk>/',
         products.DashboardUpdateView.as_view(), name='dashboard_update'),

    path('perfis/', products.ProfileProductListView.as_view(),
         name='profile_product_list'),
    path('perfis/novo/', products.ProfileProductCreate.as_view(),
         name='profile_product_create'),
    path('perfis/<int:pk>/', products.ProfileProductUpdate.as_view(),
         name='profile_product_update'),

]

speedseven/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django_select2.views import AutoResponseView

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from clients.views import clients
from core.views.core import TinyMceUploadView, TinyMceDocView
from investment.views.operations import ReceiptsView


admin.site.site_url = '/adm/inicio/'


urlpatterns = [
    path('adm/', include('core.urls')),
    path('adm/', include('emailtemplates.urls')),
    path('adm/', include('products.urls')),
    path('adm/', include('investorprofile.urls')),
    path('adm/', include('investment.urls_adm')),
    path('adm/api/', include('accounts.urls_api')),
    path('adm/usuarios/convites/', include('accounts.urls_invitation')),

    path('admin/', admin.site.urls),
    path('contas/', include('accounts.urls_account')),
    path('cliente/', include('clients.urls')),
    path('', include('website.urls')),
    path('media/private/uploads/<path:file_name>/',
         clients.ClientDocsView.as_view(), name='document_download'),

    path('media/private/receipts/<path:file_name>/',
         ReceiptsView.as_view(), name='receipts_download'),

    path('api/', include('core.urls_api')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('api/v1/', include('clients.api.urls')),

    path("select2/", include(([path("fields/auto.json", login_required(
        AutoResponseView.as_view()), name="auto-json")], 'django_select2'))),

    path(settings.TINYMCE_URL, TinyMceUploadView.as_view(),
         name='upload_tinymce_image'),

    path(settings.TINYMCE_URL+'<str:file_name>',
         TinyMceDocView.as_view(), name='tinymce_doc_image'),

]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL + 'public',
                          document_root=settings.MEDIA_ROOT / 'public')

clients/api/views.py
"""
Client api views
"""

from rest_framework import generics

from .. import models
from . import serializers


class ClientCreateView(generics.CreateAPIView):
    """
    Client create view
    """
    serializer_class = serializers.ClientSerializer
    # pylint: disable=no-member
    queryset = models.Client.objects.all()


class ClientRetrieveUpdateView(generics.RetrieveUpdateAPIView):
    """
    Client update and retrieve view
    """
    serializer_class = serializers.ClientSerializer
    # pylint: disable=no-member
    queryset = models.Client.objects.all()

clients/views/dashboards.py
"""
Dashboard JSON view
"""

from charts.views import ChartJsonView
from accounts.auth import mixins as auth_mixin

from products.models import ProductDashboard


class ClientDashboardJson(auth_mixin.LoginRequiredMixin, ChartJsonView):
    """
    Dashboars charts data in JSON format
    """

    #pylint: disable=unused-argument
    def get_dashboard(self, request, *args, **kwargs):
        """
        Get product charts according to the purchase id
        Each product may have a specific collection of charts (dashboard)
        """
        purchase_id = self.request.GET.get('purchase', None)

        if purchase_id:
            # pylint: disable=no-member
            try:
                product_dashboard = ProductDashboard.objects.get(
                    product__productpurchase__id=purchase_id)
                if product_dashboard:
                    return product_dashboard.dashboard.get_class()
            except ProductDashboard.DoesNotExist:
                pass

        return None

clients/views/mixins.py
"""
Client mixins

"""

from django.http import Http404
from accounts import roles as accounts_roles
from accounts.auth import mixins as auth_mixins
from common.views import mixins
from core import models as core_models


class ClientRoleMixin(auth_mixins.RoleMixin):
    """
    Require client role to access view
    """

    role = accounts_roles.Roles.CLIENT


class CompleteSignUpMixin(ClientRoleMixin,
                          mixins.PageMenuMixin):
    """
    Test if signup is completed
    """
    menu_template_name = 'clients/menu.html'

    skip_signup_test = False

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.is_signup_completed = False
        self.signup_context = dict()

    def get_context_data(self, **kwargs):
        """
        Insert signup complete in context
        """
        context = super().get_context_data(**kwargs)
        context['signup_completed'] = self.is_signup_completed
        context.update(self.signup_context)
        return context

    def _eval_signup_completed(self):
        """
        Check if signup is completed
        """

        client = getattr(self.request.user, 'client', None)
        client_test = client and self.request.user.client.registration_completed
        self.signup_context['registration_completed'] = client_test
        term = getattr(self.request.user, 'useracceptanceterm_set', None)

        bank_acc_set = getattr(self.request.user, 'bankaccount_set', None)
        bank_acc = None
        if bank_acc_set and bank_acc_set.exists():
            bank_acc =  bank_acc_set.filter(main_account=True).first()
            self.signup_context['bank_account'] = bank_acc

        client_test = client and self.request.user.client.registration_completed
        term = getattr(self.request.user, 'useracceptanceterm_set', None)

        term_test = term and term.filter(
            term__type=core_models.AcceptanceTerm.Type.PRIVACY_POLICY).exists()
        self.signup_context['term_acceptance_completed'] = term_test

        profile_test = self.request.user.investorprofile_set.exists()
        self.signup_context['profile_test_completed'] = profile_test

        self.is_signup_completed = client_test and term_test and profile_test

        return self.is_signup_completed

    def dispatch(self, request, *args, **kwargs):
        self.is_signup_completed = self._eval_signup_completed()
        if not self.is_signup_completed and not self.skip_signup_test:
            raise Http404()
        return super().dispatch(request, *args, **kwargs)

clients/views/operations.py
"""
Client operations views
"""

from django.urls import reverse_lazy
from investment.interfaces.views import ApplicationDepositBaseView, ApplicationWithdrawBaseView
from investment.views.operations import MoneyTransferBaseListView
from clients.views.mixins import CompleteSignUpMixin


class ClientDepositView(CompleteSignUpMixin, ApplicationDepositBaseView):
    """
    Client deposit view
    """
    success_url = reverse_lazy('clients:start_page')
    cancel_url = success_url


class ClientWithdrawView(CompleteSignUpMixin, ApplicationWithdrawBaseView):
    """
    Client withdraw view
    """
    success_url = reverse_lazy('clients:start_page')
    cancel_url = success_url


class MoneyTransferListView(CompleteSignUpMixin, MoneyTransferBaseListView):
    """
    Client account operations view
    """

    def get_queryset(self):
        return super().get_queryset().filter(application_account__user=self.request.user)

products/views/dashboards.py
"""
Dashboard JSON view
"""

from charts.views import ChartJsonView
from accounts.auth import mixins as auth_mixin

from .. import dashboards as d


class ProductsDashboardJson(auth_mixin.LoginRequiredMixin, ChartJsonView):
    """
    Dashboars charts data in JSON format
    """

    #pylint: disable=unused-argument
    def get_dashboard(self, request, *args, **kwargs):
        """
        Dashboard data
        """
        return d.ProductsDashboard

clients/templates/clients/products/products.html
{% extends 'common/page.html' %}
{% load common_tags %}

{% block content %}
<div class="container-fluid pt-2 noprint">
    <h1 class="text-success my-4 ps-4 pb-2">Nossos produtos</h1>
    
    {% if categories %}
        {% for category, products in categories.items %}
        <div class="h2 ps-4 pt-4 text-success">{% if category.show_title %}{{category.title}}{% endif %}</div>
            <div class="d-flex pe-4 flex-wrap pb-4 justify-content-center">
                {% for document in category.categorydocument_set.all %}
                <a href="{% url 'clients:category_document_detail' document.pk %}" class="mx-4 text-decoration-none text-success">{{document.display_text}} </a>
                {% endfor %}
            </div>
            <div class="row mx-1 mb-4 pb-4">
            {% for product in products %}
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="py-2">
                        <div class="card h-100">
                            <div class="card-header">
                                <div class="fw-bold fs-2 mb-2"> {{product.display_text}} </div>
                            </div>
                            <div class="card-body">
                                {% if product.briefing %}
                                <div class="row">
                                    <div class="col">
                                        <div>{{product.briefing|safe}}</div>
                                    </div>
                                </div>
                                {% endif %}
                                {%if product.application_info %}
                                <div class="row">
                                    <div class="col">
                                        <div class="mb-2"> {{product.application_info|safe}} </div>
                                    </div>
                                </div>
                                {% endif %}
                                <hr>
                                <div class="row mt-4">
                                    {% if not product.purchased %} 
                                        <div class="col text-start">
                                            <a href="{% url 'clients:products_purchase_page' product.id %}"
                                                class="btn btn-success m-auto">
                                                Saber mais e contratar
                                            </a>
                                        </div>
                                        {% else %}
                                        
                                        <div class="col text-start">
                                            <a href="{% url 'clients:products_purchase_page' product.id %}"
                                                class="btn btn-secondary m-auto">
                                                Saber mais
                                            </a>
                                        </div>
                                        <div class="col text-end pt-2"><span class="text-success fw-bold"> Contratado! </span></div>
                                        {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        {% endfor %}
    {% else %}
    <div class="row ps-4">
        <div class="col text-success">Opção indisponível no momento</div>
    </div>
    {% endif %}
</div>
{% endblock %}

clients/templates/clients/products/purchase.html
{% extends 'common/page.html' %}
{% load common_tags %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid pt-2 noprint">
    <h1 class="text-success my-4 ps-4">Contratar produto</h1>
    {% if product %}
    <form method="post" id="id_agreement_form" data-agreement-url="{% url 'products:agreement_data' %}" data-extra-args="{{purchase_form.extra_args_fields|join:','}}">
        {% csrf_token %}
        {{ purchase_form.product }}
        {% if purchase_form.product.errors %}
        <div class="row mx-4">
            <div class="col alert alert-success">
                {% for error in purchase_form.product.errors %}
                <div>{{ error|escape }}</div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <div class="row">
            <div class="col-lg-12 col-sm-12 col-md-6" id="id_product_{{product.name}}">
                <div class="p-lg-4 py-2">
                    <div class="card h-100">
                        <div class="card-header">
                            <div class="fw-bold fs-2 mb-2"> {{product.display_text}} </div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    {% if product_access %}
                                        {% if not product.purchased %}
                                        <div class="ms-4 my-4 text-start">
                                            {% if request.user.client.approved %} 
                                                
                                            {% crispy purchase_form %}
    
                                            <button name='purchase_product' id="id_purchase_product"
                                                    class="btn btn-success m-auto mb-4"
                                                    data-product="{{product.pk}}">
                                                    Contratar
                                            </button>

                                            {% else %}
                                                <p class="text-success m-auto">Você poderá contratar este produto após a aprovação do seu cadastro</p>
                                            {% endif %}
                                        </div>
                                        {% else %}
                                        <div class="ms-4 my-4 text-start">
                                            <p id="id_purchase_product" class="text-success fw-bold m-auto">
                                                Você já possui este produto
                                            </p>
                                        </div>
                                        {% endif %}
                                    {% else %}
                                        <div class="ms-4 my-4 text-start">
                                            <p class="text-success m-auto">
                                            O produto que deseja contratar não é compatível com seu perfil de investimento
                                            </p>
                                            <p class="text-success fw-bold m-auto mt-2">
                                            Você pode verificar e revisar seu enquadramento no menu "Consultas / Perfil de investimento"
                                            </p>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col ms-4">
                                     <a class="text-success" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_info" aria-expanded="false" aria-controls="collapseExample">
                                        Detalhes do investimento
                                     </a>
                                </div>
                            </div>
                            <div class="collapse" id="collapse_info">
                                <div class="row">
                                    <div class="col">
                                        <div class="product-info">
                                            {% if product.info %}
                                            <div class="px-4">{{product.info|safe}}</div>
                                            {% else %}
                                            <div class="px-4">Sem informações no momento</div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    {% else %}
    <div class="row ps-4">
        <div class="col text-success">Opção indisponível no momento</div>
    </div>
    {% endif %}
</div>

{% include 'common/agreement_modal.html' %}

{% endblock %}