clients/api/urls.py
"""
Client api urls
"""

from django.urls import path
from . import views

urlpatterns = [
    path('client/', views.ClientCreateView.as_view()),
    path('client/<int:pk>/', views.ClientRetrieveUpdateView.as_view()),
]

clients/urls.py
"""
     Urls
"""
from django.urls import path
from products.views import dashboards as core_dash_views

from .views import clients, dashboards, operations

# pylint: disable=invalid-name
app_name = 'clients'

urlpatterns = [
    path('inicio/', clients.StartView.as_view(), name='start_page'),

    path('cadastro/editar/',
         clients.ClientUpdateView.as_view(), name='client_update'),
    path('cadastro/termos-de-aceite/',
         clients.UserAcceptanceTermCreateView.as_view(), name='acceptance_term_create'),

    path('cadastro/perfil-de-investidor/',
         clients.InvestorProfileTestDetailView.as_view(), name='investor_profile_test_detail'),
    path('cadastro/perfil-de-investidor/novo/',
         clients.InvestorProfileTestCreateView.as_view(), name='investor_profile_test_create'),
    path('cadastro/perfil-de-investidor/editar/',
         clients.InvestorProfileTestUpdateView.as_view(), name='investor_profile_test_update'),

    path('cadastro/dados-bancarios/',
         clients.BankAccountListView.as_view(), name='bank_account_list'),
    path('cadastro/dados-bancarios/novo/',
         clients.BankAccountCreateView.as_view(), name='bank_account_create'),
    path('cadastro/dados-bancarios/editar/<int:pk>/',
         clients.BankAccountUpdateView.as_view(), name='bank_account_update'),

    path('produtos/', clients.ProductsView.as_view(), name='products_page'),
    path('produtos/contratar/<int:pk>',
         clients.ProductsPurchaseView.as_view(), name='products_purchase_page'),

    path('produtos/categorias/documentos/<int:pk>/',
         clients.CategoryDocumentDetailView.as_view(), name='category_document_detail'),


    path('broker/', clients.BrokerView.as_view(), name='broker_page'),

    path('consultas/extratos/', clients.ApplicationOpUserListView.as_view(),
         name='operationsstatement_page'),
    path('consultas/relatorio/', clients.ReportView.as_view(), name='report_page'),
    path('consultas/invetimentos/', clients.ProductPurcahseListView.as_view(),
         name='products_purchase_list'),
    path('consultas/invetimentos/editar/<int:pk>/',
         clients.ProductPurchaseUpdateView.as_view(), name='products_purchase_update'),
    path('consultas/contrato/<int:pk>/',
         clients.UserAgreementPrintView.as_view(), name='agreement_detail'),
    path('consultas/termos-de-aceite/',
         clients.UserAcceptanceTermListView.as_view(), name='acceptance_term_list'),
    path('consultas/termos-de-aceite/<int:pk>/',
         clients.UserAcceptanceTermPrintView.as_view(), name='acceptance_term_detail'),

    path('dashboard-data/', dashboards.ClientDashboardJson.as_view(),
         name='dashboard_client_data'),
    path('dashboard-products/', core_dash_views.ProductsDashboardJson.as_view(),
         name='dashboard_client_products_data'),

    path('trasferencias/aporte/<int:pk>/',
         operations.ClientDepositView.as_view(), name='deposit_create'),
    path('trasferencias/resgate/<int:pk>/',
         operations.ClientWithdrawView.as_view(), name='withdraw_create'),
    path('transferencias/',
         operations.MoneyTransferListView.as_view(), name='moneytransfer_list'),

    path('ajuda/', clients.HelpView.as_view(), name='help_page'),

]

core/urls.py
"""
     Urls
"""
from django.urls import path
from .views import accept_terms, core, email, bank, faq, site

# pylint: disable=invalid-name
app_name = 'core'

urlpatterns = [
    path('inicio/', core.StartView.as_view(), name='start_page'),

    path('usuarios/administradores/',
         core.AdminListView.as_view(), name='admin_list'),
    path('usuarios/administradores/editar/<int:pk>/',
         core.AdminUpdateView.as_view(), name='admin_update'),
    path('usuarios/administradores/alterar-senha/<int:pk>/',
         core.ChangeAdminPasswordView.as_view(), name='change_admin_password'),

    path('usuarios/ativacao-senha/', core.UserListView.as_view(), name='user_list'),
    path('usuarios/ativacao-senha/editar/<int:pk>/',
         core.UserUpdateView.as_view(), name='user_update'),
    path('usuarios/ativacao-senha/alterar-senha/<int:pk>/',
         core.ChangeUserPasswordView.as_view(), name='change_user_password'),

    path('usuarios/clientes/', core.ClientListView.as_view(), name='client_list'),
    path('usuarios/clientes/novo/',
         core.ClientCreateView.as_view(), name='client_create'),
    path('usuarios/clientes/editar/<int:pk>/',
         core.ClientUpdateView.as_view(), name='client_update'),

    path('usuarios/mensagens/', email.EmailListView.as_view(), name='email_list'),
    path('usuarios/mensagens/novo/',
         email.EmailCreateView.as_view(), name='email_create'),
    path('usuarios/mensagens/detalhe/<int:pk>/',
         email.EmailUpdateView.as_view(), name='email_detail'),
    path('usuarios/mensagens/log/<int:pk>/',
         email.EmailLogView.as_view(), name='email_log'),

    path('usuarios/dados-bancarios/',
         bank.BankAccountListView.as_view(), name='bank_account_list'),
    path('usuarios/dados-bancarios/novo/',
         bank.BankAccountCreateView.as_view(), name='bank_account_create'),
    path('usuarios/dados-bancarios/editar/<int:pk>/',
         bank.BankAccountUpdateView.as_view(), name='bank_account_update'),


    path('contratos/termos-de-aceite/', accept_terms.AcceptanceTermListView.as_view(),
         name='acceptance_term_list'),
    path('contratos/termos-de-aceite/novo/',
         accept_terms.AcceptanceTermCreateView.as_view(), name='acceptance_term_create'),
    path('contratos/termos-de-aceite/editar/<int:pk>/',
         accept_terms.AcceptanceTermUpdateView.as_view(), name='acceptance_term_update'),

    path('api/', core.ApiUserView.as_view(), name='api_page'),

    path('tarefas/', core.WorkflowTaskListView.as_view(), name='task_list'),

    path('configuracoes/empresa/',
         core.CompanyListView.as_view(), name='company_list'),
    path('configuracoes/empresa/novo/',
         core.CompanyCreateView.as_view(), name='company_create'),
    path('configuracoes/empresa/editar/<int:pk>/',
         core.CompanyUpdateView.as_view(), name='company_update'),

    path('configurações/faq/',
         faq.FAQConfigListView.as_view(), name='faq_config_list'),
    path('configurações/faq/novo/',
         faq.FAQConfigCreateView.as_view(), name='faq_config_create'),
    path('configurações/faq/editar/<int:pk>/',
         faq.FAQConfigUpdateView.as_view(), name='faq_config_update'),

    path('configurações/faq/questoes/',
         faq.FAQListView.as_view(), name='faq_list'),
    path('configurações/faq/questoes/novo/',
         faq.FAQCreateView.as_view(), name='faq_create'),
    path('configurações/faq/questoes/editar/<int:pk>/',
         faq.FAQUpdateView.as_view(), name='faq_update'),

    path('configuracoes/pagina-inicial/',
         site.StartPageListView.as_view(), name='start_page_list'),
    path('configuracoes/pagina-inicial/novo/',
         site.StartPageCreateView.as_view(), name='start_page_create'),
    path('configuracoes/pagina-inicial/editar/<int:pk>/',
         site.StartPageUpdateView.as_view(), name='start_page_update'),

]

speedseven/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django_select2.views import AutoResponseView

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from clients.views import clients
from core.views.core import TinyMceUploadView, TinyMceDocView
from investment.views.operations import ReceiptsView


admin.site.site_url = '/adm/inicio/'


urlpatterns = [
    path('adm/', include('core.urls')),
    path('adm/', include('emailtemplates.urls')),
    path('adm/', include('products.urls')),
    path('adm/', include('investorprofile.urls')),
    path('adm/', include('investment.urls_adm')),
    path('adm/api/', include('accounts.urls_api')),
    path('adm/usuarios/convites/', include('accounts.urls_invitation')),

    path('admin/', admin.site.urls),
    path('contas/', include('accounts.urls_account')),
    path('cliente/', include('clients.urls')),
    path('', include('website.urls')),
    path('media/private/uploads/<path:file_name>/',
         clients.ClientDocsView.as_view(), name='document_download'),

    path('media/private/receipts/<path:file_name>/',
         ReceiptsView.as_view(), name='receipts_download'),

    path('api/', include('core.urls_api')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('api/v1/', include('clients.api.urls')),

    path("select2/", include(([path("fields/auto.json", login_required(
        AutoResponseView.as_view()), name="auto-json")], 'django_select2'))),

    path(settings.TINYMCE_URL, TinyMceUploadView.as_view(),
         name='upload_tinymce_image'),

    path(settings.TINYMCE_URL+'<str:file_name>',
         TinyMceDocView.as_view(), name='tinymce_doc_image'),

]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL + 'public',
                          document_root=settings.MEDIA_ROOT / 'public')

clients/api/views.py
"""
Client api views
"""

from rest_framework import generics

from .. import models
from . import serializers


class ClientCreateView(generics.CreateAPIView):
    """
    Client create view
    """
    serializer_class = serializers.ClientSerializer
    # pylint: disable=no-member
    queryset = models.Client.objects.all()


class ClientRetrieveUpdateView(generics.RetrieveUpdateAPIView):
    """
    Client update and retrieve view
    """
    serializer_class = serializers.ClientSerializer
    # pylint: disable=no-member
    queryset = models.Client.objects.all()

clients/views/dashboards.py
"""
Dashboard JSON view
"""

from charts.views import ChartJsonView
from accounts.auth import mixins as auth_mixin

from products.models import ProductDashboard


class ClientDashboardJson(auth_mixin.LoginRequiredMixin, ChartJsonView):
    """
    Dashboars charts data in JSON format
    """

    #pylint: disable=unused-argument
    def get_dashboard(self, request, *args, **kwargs):
        """
        Get product charts according to the purchase id
        Each product may have a specific collection of charts (dashboard)
        """
        purchase_id = self.request.GET.get('purchase', None)

        if purchase_id:
            # pylint: disable=no-member
            try:
                product_dashboard = ProductDashboard.objects.get(
                    product__productpurchase__id=purchase_id)
                if product_dashboard:
                    return product_dashboard.dashboard.get_class()
            except ProductDashboard.DoesNotExist:
                pass

        return None

clients/views/mixins.py
"""
Client mixins

"""

from django.http import Http404
from accounts import roles as accounts_roles
from accounts.auth import mixins as auth_mixins
from common.views import mixins
from core import models as core_models


class ClientRoleMixin(auth_mixins.RoleMixin):
    """
    Require client role to access view
    """

    role = accounts_roles.Roles.CLIENT


class CompleteSignUpMixin(ClientRoleMixin,
                          mixins.PageMenuMixin):
    """
    Test if signup is completed
    """
    menu_template_name = 'clients/menu.html'

    skip_signup_test = False

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.is_signup_completed = False
        self.signup_context = dict()

    def get_context_data(self, **kwargs):
        """
        Insert signup complete in context
        """
        context = super().get_context_data(**kwargs)
        context['signup_completed'] = self.is_signup_completed
        context.update(self.signup_context)
        return context

    def _eval_signup_completed(self):
        """
        Check if signup is completed
        """

        client = getattr(self.request.user, 'client', None)
        client_test = client and self.request.user.client.registration_completed
        self.signup_context['registration_completed'] = client_test
        term = getattr(self.request.user, 'useracceptanceterm_set', None)

        bank_acc_set = getattr(self.request.user, 'bankaccount_set', None)
        bank_acc = None
        if bank_acc_set and bank_acc_set.exists():
            bank_acc =  bank_acc_set.filter(main_account=True).first()
            self.signup_context['bank_account'] = bank_acc

        client_test = client and self.request.user.client.registration_completed
        term = getattr(self.request.user, 'useracceptanceterm_set', None)

        term_test = term and term.filter(
            term__type=core_models.AcceptanceTerm.Type.PRIVACY_POLICY).exists()
        self.signup_context['term_acceptance_completed'] = term_test

        profile_test = self.request.user.investorprofile_set.exists()
        self.signup_context['profile_test_completed'] = profile_test

        self.is_signup_completed = client_test and term_test and profile_test

        return self.is_signup_completed

    def dispatch(self, request, *args, **kwargs):
        self.is_signup_completed = self._eval_signup_completed()
        if not self.is_signup_completed and not self.skip_signup_test:
            raise Http404()
        return super().dispatch(request, *args, **kwargs)

clients/views/operations.py
"""
Client operations views
"""

from django.urls import reverse_lazy
from investment.interfaces.views import ApplicationDepositBaseView, ApplicationWithdrawBaseView
from investment.views.operations import MoneyTransferBaseListView
from clients.views.mixins import CompleteSignUpMixin


class ClientDepositView(CompleteSignUpMixin, ApplicationDepositBaseView):
    """
    Client deposit view
    """
    success_url = reverse_lazy('clients:start_page')
    cancel_url = success_url


class ClientWithdrawView(CompleteSignUpMixin, ApplicationWithdrawBaseView):
    """
    Client withdraw view
    """
    success_url = reverse_lazy('clients:start_page')
    cancel_url = success_url


class MoneyTransferListView(CompleteSignUpMixin, MoneyTransferBaseListView):
    """
    Client account operations view
    """

    def get_queryset(self):
        return super().get_queryset().filter(application_account__user=self.request.user)

investment/views/operations.py
"""
Aplication account operations views
"""

from django.urls import reverse_lazy

from accounts.auth import mixins as auth_mixins
from accounts import roles as accounts_roles
from common.forms import mixins as form_mixins
from common.messages import message_add
from common.views import generic, mixins
from investment import models

from .. import forms, tables
from ..models import ApplicationAccount


class OperationBaseView(mixins.AdminMixin, form_mixins.LoggedUserMixin, generic.FormView):
    """
    Base view for admin direct deposit and witdraw
    """

    success_url = reverse_lazy('investment:applicationaccount_list')
    template_name = 'common/form.html'
    cancel_url = success_url
    success_message = 'Depósito realizado com sucesso!'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        #pylint: disable=no-member
        kwargs['application_account'] = ApplicationAccount.objects.get(
            pk=self.kwargs['pk'])
        return kwargs

    def form_valid(self, form):
        # Form is not automatically saved
        form.save()
        message_add(self.request, self.success_message)
        return super().form_valid(form)


class DepositView(OperationBaseView):
    """
    View for make deposit
    """
    form_class = forms.DepositiForm
    title = "Aporte direto"
    success_message = 'Depósito realizado com sucesso!'


class WithdrawView(OperationBaseView):
    """
    View for make withdraw
    """
    form_class = forms.WithdrawForm
    title = "Retirada direta"
    success_message = 'Retirada realizada com sucesso!'


class CloseApplicationView(OperationBaseView):
    """
    View for make withdraw
    """
    form_class = forms.CloseApplicationForm
    title = "Encerrar aplicação"
    success_message = 'Aplicação encerrada com sucesso!'

    def get_controls(self):
        controls = super().get_controls()
        controls[1].text = "Encerrar aplicação"
        return controls


class MoneyTransferBaseListView(mixins.ListViewMixin):
    """
    Money transfer base
    """

    model = models.MoneyTransfer
    table_class = tables.MoneyTransferBaseTable
    template_name = 'common/list.html'
    title = 'Solicitações de aportes e resgates'


class MoneyTransferListView(mixins.AdminMixin, MoneyTransferBaseListView):
    """
    Money transfer
    """

    table_class = tables.MoneyTransferTable
    title = 'Solicitações de transferência'


class AccountOpScheduleListView(mixins.AdminMixin, mixins.ListViewMixin):
    """
    List of applications
    """
    model = models.AccountOpSchedule
    table_class = tables.AccountOpScheduleTable
    template_name = 'common/list.html'
    title = 'Agendamentos'


class ReceiptsView(auth_mixins.LoginRequiredMixin, generic.FileBaseView):
    """
    View to show/download operations receipts
    """

    model = models.MoneyTransfer
    field = 'receipt_file'
    media_file_root = 'private/receipts/'

    def can_access_file(self, request):
        user = request.user
        roles = [accounts_roles.Roles.ADMIN, accounts_roles.Roles.CLIENT]
        if accounts_roles.has_role_in(user, roles):
            return True
        return False

clients/templates/clients/start/chart_area.html
<div class="row gx-2">
    {% if widgets|length == 1 %}

    {% for widget in widgets %}
    <div class="col-lg-12 col-md-12 col-sm-12 text-white">
        <div class="card">
            <div class="card-header">
                {{widget.name}}
            </div>
            <div class="card-body" style="min-height: 600px; height: 600px">
                {{widget.template|safe}}
            </div>
        </div>
    </div>
    {% endfor %}

    {% elif widgets|length == 2 %}

    {% for widget in widgets %}
    <div class="col-6 col-lg-6 col-md-12 col-sm-12 text-white pb-2">
        <div class="card">
            <div class="card-header">
                {{widget.name}}
            </div>
            <div class="card-body" style="min-height: 400px; height: 400px">
                {{widget.template|safe}}
            </div>
        </div>
    </div>
    {% endfor %}

    {% else %}

    {% for widget in widgets %}
    <div class="col-lg-4 col-md-12 col-sm-12 text-white pb-2">
        <div class="card">
            <div class="card-header">
                {{widget.name}}
            </div>
            <div class="card-body" style="min-height: 350px; height: 350px">
                {{widget.template|safe}}
            </div>
        </div>
    </div>
    {% endfor %}

    {% endif %}
</div>

clients/templates/clients/start/client_info.html
{% load common_tags %}
<div class="card" onclick="location.href='{% url 'clients:client_update' %}';" style="cursor: pointer;">
    <div class="card-body p-0">
        <div class="row">
            <div class="col d-flex text-center justify-content-center">
                <p class="btn user-picture align-items-center">
                    <span class="h1" style="font-size: 4.5rem;">{{request.user.first_name.0}}</span>
                </p>
            </div>
            <div class="col text-center">
                <p class="pt-2 pb-0 m-0">{{user.get_full_name}}</p>
                <p class="text-secondary p-0 m-0">{{user.email}}</p>
            </div>
        </div>
    </div>
</div>

clients/templates/clients/start/high_risk_dash.html
<div class="row">
    <div class="col-md-4 p-3">
        <div class="shadow-sm bg-body rounded" id="card_id1"></div>
    </div>
    <div class="col-md-4 p-3">
        <div class="shadow-sm bg-body rounded" id="card_id2"></div>
    </div>
    <div class="col-md-4 p-3">
        <div class="shadow-sm bg-body rounded" id="card_id3"></div>
    </div>
</div>
<div class="row" >
    <div class="col-md-6" style="height:335px;">
        <div class="shadow-sm p-3  bg-body rounded" id="line_chart_id1"></div>
    </div>
    <div class="col-md-6" style="height:300px">
        <div class="shadow-sm p-3 bg-body rounded" id="line_chart_id2"></div>
    </div>
</div>
<div class="row mt-4" >
    <div class="col-md-6" style="height:300px">
        <div class="shadow-sm p-3 bg-body rounded" id="line_chart_id3"></div>
    </div>
    <div class="col-md-6" style="height:300px">
        <div class="shadow-sm p-3 bg-body rounded" id="line_chart_id4"></div>
    </div>
</div>

clients/templates/clients/start/invest.html
<div class="card ">
    <div class="card-header">
        <div class="h4 text-primary">
            Invista agora
        </div>
    </div>
    <div class="card-body  m-0 p-2">
        <table class='table table-sm table-borderless'>
            <body>
                {% if products %}
                <tr>
                    <td><a class="btn text-primary p-0 m-0" href="{% url 'clients:products_page' %}">Nossos produtos</a></td>
                    <td class="text-end"><a class="page-menu-link" href="{% url 'clients:products_page' %}"><i
                                class="bi bi-bag btn text-primary p-0 m-0 "></a></i></td>
                </tr>
                <tr>
                    <td><a class="btn text-primary p-0 m-0" href="{% url 'clients:broker_page' %}">Daytrade</a></td>
                    <td class="text-end"><a class="page-menu-link" href="{% url 'clients:broker_page' %}"><i
                                class="bi bi-box-arrow-right btn text-primary p-0 m-0 "></a></i></td>
                </tr>
                <tr>
                    <td class="text-muted">Swingtrade</td>
                    <td class="text-end"></td>
                </tr>
                <tr>
                    <td>
                        <a class="btn p-0 text-{% if not request.user.bankaccount.bank.name %}danger{% else %}primary{% endif %}" 
                        data-bs-toggle="collapse" data-bs-target="#bank_data"
                            aria-expanded="false" aria-controls="collapseExample"
                            >
                            Dados bancários
                        </a>
                    </td>
                    <td class="text-end" data-bs-toggle="collapse" data-bs-target="#bank_data">
                        <i class="bi bi-bank btn text-primary p-0 m-0"></i>
                    </td>
                </tr>
                {% else %}
                <tr>
                    <td>
                        <a class="btn  p-0 m-0 text-decoration-none" href="{% url 'clients:products_page' %}">
                        <span class="h5 text-success">Comece contratando um de nossos produtos</span></a>
                    </td>
                    <td class="text-end"><a class="text-decoration-none" href="{% url 'clients:products_page' %}"></a></td>
                </tr>
                {% endif %}
            </body>
        </table>

        <div class="collapse" id="bank_data">
            <div class=" pb-3 px-3">
                <table class='table table-sm'>

                    <body>
                        <tr>
                            {% if request.user.bankaccount.bank.name %}
                            <td colspan="2">{{request.user.bankaccount.bank.name}}</td>
                            {% else %}
                            <td colspan="2"><span class="text-muted">Conta não cadastrada</span></td>
                            {% endif %}
                        </tr>
                        <tr>
                            <td class="">ISPB</td>
                            <td class="text-end">{{request.user.bankaccount.bank.ispb|default:'-----'}}
                            </td>
                        </tr>
                        <tr>
                            <td class="">Agência</td>
                            <td class="text-end">
                                <span>{{request.user.bankaccount.branch|default:'-----'}}</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="">Conta</td>
                            <td class="text-end">{{request.user.bankaccount.account|default:'-----'}}
                            </td>
                        </tr>
                        <tr>
                            <td class="text-secondary">SFWIT</td>
                            <td class="text-end"></td>
                        </tr>
                    </body>
                </table>
            </div>
        </div>
    </div>
</div>

clients/templates/clients/start/operations.html
{% load common_tags %}
<div class="card">
    <div class="card-body m-0 p-2">
        <div class="row">
            {% if request.user.client.approved and bank_account.approved %} 
                <div class="col-6 dropdown">
                        <a class="btn btn-secondary w-100 mb-2 dropdown-toggle" href="#" role="button" id="dropdownWithdraw" data-bs-toggle="dropdown" aria-expanded="false">
                            Resgate
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownDeposit">
                        {% for withdraw in operations.withdraw %}
                            <li><a class="dropdown-item" href="{% url 'clients:withdraw_create' withdraw.application_account_id %}">{{withdraw.product}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-6 dropdown">
                        <a class="btn btn-success w-100 mb-2 dropdown-toggle" href="#" role="button" id="dropdownDeposit" data-bs-toggle="dropdown" aria-expanded="false">
                            Aporte
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownWithdraw">
                        {% for deposit in operations.deposit %}
                            <li><a class="dropdown-item" href="{% url 'clients:deposit_create' deposit.application_account_id %}">{{deposit.product}}</a></li>
                            {% endfor %}
                        </ul>
                </div>
            {% else %}
                <div class="col">
                    {% if not request.user.client.approved %}
                    <p>Você solicitou uma modificação em seu <strong>cadastro</strong>. As operações de aporte e resgate estarão disponíveis após aprovação.</p>
                    <a href="{% url 'clients:client_update' %}" class="btn btn-success w-100">
                        Consultar cadastro
                    </a>
                    {% elif not bank_account %}
                    <p>Cadastre sua <strong>conta bancária principal</strong>. As operações de aporte e resgate estarão disponíveis após aprovação.</p>
                    <a href="{% url 'clients:bank_account_list' %}" class="btn btn-success w-100">
                        Dados bancários
                    </a>
                    {% elif not bank_account.approved %}
                    <p>Seus dados bancários estão aguardando aprovação. As operações de aporte e resgate estarão disponíveis após aprovação.</p>
                    <a href="{% url 'clients:bank_account_list' %}" class="btn btn-success w-100">
                        Dados bancários
                    </a>
                    {% endif %}        
                </div>
            {% endif %}
        </div>
    </div>
</div>

clients/templates/clients/start/start.html
{% extends 'common/page.html' %}
{% load common_tags %}



{% block menu %}

 {{block.super}}

<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js" async>
    {
    "symbols": [
      {
        "proName": "FOREXCOM:SPXUSD",
        "title": "S&P 500"
      },
      {
        "proName": "FOREXCOM:NSXUSD",
        "title": "US 100"
      },
      {
        "proName": "FX_IDC:EURUSD",
        "title": "EUR/USD"
      },
      {
        "proName": "BITSTAMP:BTCUSD",
        "title": "Bitcoin"
      },
      {
        "proName": "BITSTAMP:ETHUSD",
        "title": "Ethereum"
      }
    ],
    "showSymbolLogo": true,
    "colorTheme": "{{request.theme}}",
    "isTransparent": true,
    "displayMode": "adaptive",
    "locale": "br"
  }
    </script>
  </div>
  <!-- TradingView Widget END -->
{% endblock %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row gx-2">
        {% if products %}
        <div class="col-lg-3" id="col_left_id">
        {% else %}
        <div class="col-lg-3 order-lg-first order-last" id="col_left_id">
        {% endif %}    
            <div class="d-flex flex-column bd-highlight mb-3">
                <div class="mb-2">{% include 'clients/start/client_info.html' %}</div>
                {% if products %}
                <div class="mb-2">{% include 'clients/start/overview.html' %}</div>
                <div class="mb-2">{% include 'clients/start/operations.html' %}</div>
                <div class="mb-2">{% include 'clients/start/my_produts.html' %}</div>
                {% endif %}
                <div class="mb-2">{% include 'clients/start/currency.html' %}</div>
            </div>
        </div>
        {% if products %}
        <div class="col-lg-9 mb-0 pb-0 main-dashboard">
            {% include 'clients/start/chart_area.html' %}
        </div>
        {% else %}
        <div class="col-lg-9 m-0 p-0 main-dashboard">
          <div class="row justify-content-center mx-1 mb-2">
            <div class="card">
              <div class="card-header">
                {% if request.user.client.approved %}
                <div class="h1 text-center">
                  Invista agora
                </div>
                <div class="card-body px-0 text-center">
                  <a class="btn btn-lg btn-success text-decoration-none" href="{% url 'clients:products_page' %}">
                    <span class="h3 text-dark">Contrate um de nossos produtos</span></a>
                </div>
                {% else %}
                <div class="h1 text-center">
                  Abertura de conta em análise
                </div>
                <div class="card-body px-0 text-center">
                  <a class="btn btn-lg btn-success text-decoration-none" href="{% url 'clients:client_update' %}">
                    <span class="h3 text-dark">Consulte seu cadastro</span></a>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        {% endif %}
    </div>

    {% include 'common/document_modal.html' %}

    {% for message in messages %}
    {% if 'core_modal' in message.extra_tags %}
    {% include 'common/message_modal.html' %}
    {% endif %}
    {% endfor %}


    {% endblock %}