core/urls.py
"""
     Urls
"""
from django.urls import path
from .views import accept_terms, core, email, bank, faq, site

# pylint: disable=invalid-name
app_name = 'core'

urlpatterns = [
    path('inicio/', core.StartView.as_view(), name='start_page'),

    path('usuarios/administradores/',
         core.AdminListView.as_view(), name='admin_list'),
    path('usuarios/administradores/editar/<int:pk>/',
         core.AdminUpdateView.as_view(), name='admin_update'),
    path('usuarios/administradores/alterar-senha/<int:pk>/',
         core.ChangeAdminPasswordView.as_view(), name='change_admin_password'),

    path('usuarios/ativacao-senha/', core.UserListView.as_view(), name='user_list'),
    path('usuarios/ativacao-senha/editar/<int:pk>/',
         core.UserUpdateView.as_view(), name='user_update'),
    path('usuarios/ativacao-senha/alterar-senha/<int:pk>/',
         core.ChangeUserPasswordView.as_view(), name='change_user_password'),

    path('usuarios/clientes/', core.ClientListView.as_view(), name='client_list'),
    path('usuarios/clientes/novo/',
         core.ClientCreateView.as_view(), name='client_create'),
    path('usuarios/clientes/editar/<int:pk>/',
         core.ClientUpdateView.as_view(), name='client_update'),

    path('usuarios/mensagens/', email.EmailListView.as_view(), name='email_list'),
    path('usuarios/mensagens/novo/',
         email.EmailCreateView.as_view(), name='email_create'),
    path('usuarios/mensagens/detalhe/<int:pk>/',
         email.EmailUpdateView.as_view(), name='email_detail'),
    path('usuarios/mensagens/log/<int:pk>/',
         email.EmailLogView.as_view(), name='email_log'),

    path('usuarios/dados-bancarios/',
         bank.BankAccountListView.as_view(), name='bank_account_list'),
    path('usuarios/dados-bancarios/novo/',
         bank.BankAccountCreateView.as_view(), name='bank_account_create'),
    path('usuarios/dados-bancarios/editar/<int:pk>/',
         bank.BankAccountUpdateView.as_view(), name='bank_account_update'),


    path('contratos/termos-de-aceite/', accept_terms.AcceptanceTermListView.as_view(),
         name='acceptance_term_list'),
    path('contratos/termos-de-aceite/novo/',
         accept_terms.AcceptanceTermCreateView.as_view(), name='acceptance_term_create'),
    path('contratos/termos-de-aceite/editar/<int:pk>/',
         accept_terms.AcceptanceTermUpdateView.as_view(), name='acceptance_term_update'),

    path('api/', core.ApiUserView.as_view(), name='api_page'),

    path('tarefas/', core.WorkflowTaskListView.as_view(), name='task_list'),

    path('configuracoes/empresa/',
         core.CompanyListView.as_view(), name='company_list'),
    path('configuracoes/empresa/novo/',
         core.CompanyCreateView.as_view(), name='company_create'),
    path('configuracoes/empresa/editar/<int:pk>/',
         core.CompanyUpdateView.as_view(), name='company_update'),

    path('configurações/faq/',
         faq.FAQConfigListView.as_view(), name='faq_config_list'),
    path('configurações/faq/novo/',
         faq.FAQConfigCreateView.as_view(), name='faq_config_create'),
    path('configurações/faq/editar/<int:pk>/',
         faq.FAQConfigUpdateView.as_view(), name='faq_config_update'),

    path('configurações/faq/questoes/',
         faq.FAQListView.as_view(), name='faq_list'),
    path('configurações/faq/questoes/novo/',
         faq.FAQCreateView.as_view(), name='faq_create'),
    path('configurações/faq/questoes/editar/<int:pk>/',
         faq.FAQUpdateView.as_view(), name='faq_update'),

    path('configuracoes/pagina-inicial/',
         site.StartPageListView.as_view(), name='start_page_list'),
    path('configuracoes/pagina-inicial/novo/',
         site.StartPageCreateView.as_view(), name='start_page_create'),
    path('configuracoes/pagina-inicial/editar/<int:pk>/',
         site.StartPageUpdateView.as_view(), name='start_page_update'),

]

emailtemplates/urls.py
"""
     Urls
"""
from django.urls import path
from . import views

# pylint: disable=invalid-name
app_name = 'emailtemplate'

urlpatterns = [
    path('modelo-de-email/', views.EmailTemplateListView.as_view(), name='emailtemplate_list'),
    path('modelo-de-email/novo/',
         views.EmailTemplateCreateView.as_view(), name='emailtemplate_create'),
    path('modelo-de-email/editar/<int:pk>/',
         views.EmailTemplateUpdateView.as_view(), name='emailtemplate_update'),

]

investorprofile/urls.py
"""
     Urls
"""
from django.urls import path

from . import views

# pylint: disable=invalid-name
app_name = 'investorprofile'

urlpatterns = [
    path('teste-de-perfil/', views.ProfileTestListView.as_view(),
         name='profile_test_list'),

    path('teste-de-perfil/editar/<int:pk>/',
         views.ProfileTestUpdateView.as_view(), name='profile_test_update'),

    path('teste-de-perfil/preview/<int:pk>/', views.ProfileTestDetailView.as_view(),
         name='profile_test_detail'),

]

products/urls.py
"""
     Urls
"""
from django.urls import path

from .views import agreements, products

# pylint: disable=invalid-name
app_name = 'products'

urlpatterns = [

    path('contratos/produtos/', agreements.AgreementListView.as_view(),
         name='agreement_list'),
    path('contratos/produtos/novo/',
         agreements.AgreementCreateView.as_view(), name='agreement_create'),
    path('contratos/produtos/editar/<int:pk>/',
         agreements.AgreementUpdateView.as_view(), name='agreement_update'),
    path('contratos/produtos/dados/',
         agreements.AgreementJsonView.as_view(), name='agreement_data'),
    path('contrato/preview/<int:pk>/',
         agreements.UserAgreementPreview.as_view(), name='agreement_preview'),
    path('contrato-cliente/<int:pk>/',
         agreements.UserAgreementPrintView.as_view(), name='agreement_detail'),

    path('produtos/', products.ProductListView.as_view(), name='product_list'),
    path('produtos/novo/',
         products.ProductCreateView.as_view(), name='product_create'),
    path('produtos/editar/<int:pk>/',
         products.ProductUpdateView.as_view(), name='product_update'),
    path('produto-info/', products.ProductJsonData.as_view(), name='product_info_js'),
    path('produtos-contratados/', products.ProductPurchaseListView.as_view(),
         name='product_purchase_list'),

    path('produtos/categorias/',
         products.ProductCategoryListView.as_view(), name='category_list'),
    path('produtos/categorias/novo/',
         products.ProductCategoryCreateView.as_view(), name='category_create'),
    path('produtos/categorias/editar/<int:pk>/',
         products.ProductCategoryUpdateView.as_view(), name='category_update'),

    path('produtos/categorias/documentos/',
         products.CategoryDocumentListView.as_view(), name='category_document_list'),
    path('produtos/categorias/documento/novo/',
         products.CategoryDocumentCreateView.as_view(), name='category_document_create'),
    path('produtos/categorias/documentos/editar/<int:pk>/',
         products.CategoryDocumentUpdateView.as_view(), name='category_document_update'),

    path('dashboads/', products.DashboardListView.as_view(),
         name='dashboard_list'),
    path('dashboads/novo/',
         products.DashboardCreateView.as_view(), name='dashboard_create'),
    path('dashboads/editar/<int:pk>/',
         products.DashboardUpdateView.as_view(), name='dashboard_update'),

    path('perfis/', products.ProfileProductListView.as_view(),
         name='profile_product_list'),
    path('perfis/novo/', products.ProfileProductCreate.as_view(),
         name='profile_product_create'),
    path('perfis/<int:pk>/', products.ProfileProductUpdate.as_view(),
         name='profile_product_update'),

]

speedseven/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django_select2.views import AutoResponseView

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from clients.views import clients
from core.views.core import TinyMceUploadView, TinyMceDocView
from investment.views.operations import ReceiptsView


admin.site.site_url = '/adm/inicio/'


urlpatterns = [
    path('adm/', include('core.urls')),
    path('adm/', include('emailtemplates.urls')),
    path('adm/', include('products.urls')),
    path('adm/', include('investorprofile.urls')),
    path('adm/', include('investment.urls_adm')),
    path('adm/api/', include('accounts.urls_api')),
    path('adm/usuarios/convites/', include('accounts.urls_invitation')),

    path('admin/', admin.site.urls),
    path('contas/', include('accounts.urls_account')),
    path('cliente/', include('clients.urls')),
    path('', include('website.urls')),
    path('media/private/uploads/<path:file_name>/',
         clients.ClientDocsView.as_view(), name='document_download'),

    path('media/private/receipts/<path:file_name>/',
         ReceiptsView.as_view(), name='receipts_download'),

    path('api/', include('core.urls_api')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('api/v1/', include('clients.api.urls')),

    path("select2/", include(([path("fields/auto.json", login_required(
        AutoResponseView.as_view()), name="auto-json")], 'django_select2'))),

    path(settings.TINYMCE_URL, TinyMceUploadView.as_view(),
         name='upload_tinymce_image'),

    path(settings.TINYMCE_URL+'<str:file_name>',
         TinyMceDocView.as_view(), name='tinymce_doc_image'),

]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL + 'public',
                          document_root=settings.MEDIA_ROOT / 'public')

core/views/accept_terms.py
"""
    Agreement views
"""
from django.urls import reverse_lazy

from common.views import generic, mixins


from core.models import AcceptanceTerm
from core.forms.core import AccepanceTermForm

from .. import tables


class AcceptanceTermListView(mixins.AdminMixin,
                             mixins.ListViewMixin):
    """
    Acceptance terms list
    """
    model = AcceptanceTerm
    table_class = tables.AcceptanceTable
    template_name = 'common/list.html'
    title = 'Termos de aceite'
    controls = [
        {'link': {'text': 'Novo', 'url': 'core:acceptance_term_create'}},
    ]

    def get_queryset(self):
        return super().get_queryset().order_by('type', '-version')


class AcceptanceTermCreateView(mixins.AdminMixin,
                               generic.CreateView):
    """
    Create acceptance term
    """
    model = AcceptanceTerm
    form_class = AccepanceTermForm
    template_name = 'common/form.html'
    title = 'Termo de aceite'
    success_url = reverse_lazy('core:acceptance_term_list')
    cancel_url = success_url


class AcceptanceTermUpdateView(mixins.AdminMixin,
                               generic.UpdateView):
    """
    Update agreement
    """
    model = AcceptanceTerm
    form_class = AccepanceTermForm
    template_name = 'common/form.html'
    title = 'Termo de aceite'
    success_url = reverse_lazy('core:acceptance_term_list')
    cancel_url = success_url

core/views/bank.py
"""
Admin bank views
"""

from django.urls import reverse_lazy
from common.views import mixins
from investment.views import bank
from investment import tables as invest_tables
from investment.forms import BankFilterForm


class BankAccountListView(mixins.AdminMixin,
                          BankFilterForm,
                          bank.BankAccountBaseListView):
    """
    Client bank account list
    """

    table_class = invest_tables.bank_account_table(
        'core:bank_account_update', exclude_owner=False)

    controls = [
        {'link': {'text': 'Novo', 'url': 'core:bank_account_create'}},
    ]


class BankAccountCreateView(mixins.AdminMixin,
                            bank.BankAccountCreateView):
    """
    Client bank account create
    """

    success_url = reverse_lazy('core:bank_account_list')
    cancel_url = success_url


class BankAccountUpdateView(mixins.AdminMixin,
                            bank.BankAccountUpdateView):
    """
    Client bank account update
    """

    success_url = reverse_lazy('core:bank_account_list')
    cancel_url = success_url

core/views/email.py
"""
Email views
"""

from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse_lazy

from common.views import generic, mixins
from core import models, tables, tasks
from core.forms import email


class EmailListView(mixins.AdminMixin,
                    mixins.WebsockeMixin,
                    mixins.ListViewMixin):
    """
        Admin list
    """
    model = models.EmailBatchMessage
    table_class = tables.EmailBatchTable
    template_name = 'common/list.html'
    title = 'Mensagens'
    socket_name = 'send_batch_email'
    controls = [
        {'link': {'text': 'Novo', 'url': 'core:email_create'}},
    ]


class EmailCreateView(mixins.AdminMixin,
                      generic.CreateView):
    """
    Email create view to send email to user group according to user role
    """
    model = models.EmailBatchMessage
    form_class = email.EmailBatchForm
    template_name = 'common/form.html'
    title = 'Nova mensagem'
    success_url = reverse_lazy('core:email_list')
    cancel_url = success_url

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        return response

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        # For some unknown reason, if message readonly is set to True in the
        # update view it must be set to False here
        form.fields['message'].widget.mce_attrs.update({'readonly': False})
        return form

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        try:
            response = super().form_valid(form)
            tasks.send_email.delay(self.object.pk)
        except Exception as err:
            form.add_error(None, 'Problema ao enviar email em segundo plano.')
            form.add_error(None, str(err))
            response = self.form_invalid(form)
            self.object.delete()

        return response

    def get_controls(self):
        """
        Default form controls list
        """
        controls = super().get_controls()
        controls[1].text = 'Enviar'
        return controls

    def get_success_message(self):
        return "Envio de email agendado"


class EmailUpdateView(mixins.AdminMixin,
                      generic.UpdateView):
    """
    Email update view to send email to user group according to user role
    """
    model = models.EmailBatchMessage
    form_class = email.EmailBatchForm
    template_name = 'common/form.html'
    title = 'Mensagem enviada'
    success_url = reverse_lazy('core:email_list')
    cancel_url = success_url

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        for _key, field in form.fields.items():
            field.disabled = True
        # Set to readonly keeps it state even if the view accessed after this is the
        # create view (for some unknown reason)
        form.fields['message'].widget.mce_attrs.update({'readonly': True})
        return form

    def form_valid(self, form):
        status = models.EmailBatchMessage.Status
        if self.object.status in status.FINISHED:
            return HttpResponseBadRequest('O email não pode ser editado')
        else:
            tasks.send_email.delay(self.object.pk)
            return HttpResponseRedirect(self.success_url)

    def get_controls(self):
        "Only cancel button is kept"
        controls = super().get_controls()
        controls.pop(1)
        status = models.EmailBatchMessage.Status
        if self.object.status in status.FINISHED:
            controls.pop(1)
        elif self.object.status == status.FINISHED_ERR:
            controls[1].text = "Reenviar (apenas falhos)"
        elif self.object.status in [status.PROCESSING, status.WAITING]:
            controls[1].text = "Reenviar (apenas não enviados)"

        return controls


class EmailLogView(mixins.AdminMixin,
                   mixins.ListViewMixin):
    """
        Admin list
    """
    model = models.EmailBatchRecipient
    table_class = tables.EmailBatchRecipientTable
    template_name = 'common/list.html'
    title = 'Log de mensagens'
    socket_name = 'send_batch_email'

    def get_queryset(self):
        return super().get_queryset().filter(email_batch=self.kwargs['pk'])

core/views/site.py
from django.urls import reverse_lazy

from core import tables
from core.forms.site import StartPageForm
from .core import CompanyListView, CompanyCreateView, CompanyUpdateView


class StartPageListView(CompanyListView):
    """
    Start page list
    """
    title = 'Página inicial'
    table_class = tables.StartPageTable
    controls = [
        {'link': {'text': 'Criar', 'url': 'core:start_page_create'}},
    ]


class StartPageCreateView(CompanyCreateView):
    """
    Create start page
    """
    title = 'Página inicial'
    form_class = StartPageForm

    success_url = reverse_lazy('core:start_page_list')
    cancel_url = success_url


class StartPageUpdateView(CompanyUpdateView):
    """
    Update start page
    """
    title = 'Página inicial'
    form_class = StartPageForm
    success_url = reverse_lazy('core:start_page_list')
    cancel_url = success_url

core/templates/core/api_user_menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'core:start_page' %}">Speed7</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="page-menu-link nav-link active" aria-current="page" 
                        href="{% url 'core:api_page' %}">
                        <i class="bi bi-house"></i> Home
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        {{request.user.email}}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item btn" data-bs-toggle="modal" data-bs-target="#logout_modal">
                                <i class="bi bi-box-arrow-right"></i> Sair
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% include 'account/logout_modal.html' %}

core/templates/core/api_user_start.html
{% extends 'common/page.html' %}

{% block content %}
<div class="container-fluid">
    <div class="d-flex justify-content-center align-items-center p-4">
        <div class="card bg-light">
            <div class="card-header">
                <div class="h4 text-primary">
                    Acesso à API
                </div>
            </div>
            <div class="card-body bg-light m-0 p-2">
                <table class='table table-sm'>
                    <body>
                        <tr>
                            <td>
                                <a class="p-0 m-0" href="{% url 'schema-redoc' %}"> Documentação </a>
                            </td>
                        </tr>
                        {% if not api_production_mode %}
                        <tr>
                            <td>
                                <a class="p-0 m-0" href="{% url 'schema-swagger-ui' %}"> Interface para api </a>
                            </td>
                        </tr>
                        {% endif %}
                    </body>
                </table>

            </div>
        </div>
    </div>
</div>

{% endblock %}

core/templates/core/menu.html
{% extends 'common/menu.html' %}


{% block navigation_menu %}
<li class="nav-item">
    <a class="page-menu-link nav-link" aria-current="page" href="{% url 'core:start_page' %}">
        <i class="bi bi-house"></i> Home
    </a>
</li>

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownHelp" role="button"
        data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-people"></i> Usuários
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownHelp">
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'core:admin_list' %}"><i
                    class="bi bi-person-badge"></i> Administradores</a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'core:user_list' %}">
                <i class="bi bi-people"></i> Ativação e senha</a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'core:client_list' %}">
                <i class="bi bi-people"></i> Clientes</a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'core:bank_account_list' %}"><i
                    class="bi bi-pencil-square"></i> Dados bancários</a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'core:task_list' %}"><i
                    class="bi bi-pencil-square"></i> Aprovações</a>
        </li>
    </ul>
</li>

{% if request.user.is_staff %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownHelp" role="button"
        data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-envelope"></i> Email
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownHelp">
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'invitations:invitation_list' %}"><i
                    class="bi bi-envelope-plus"></i>
                Convites</a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'core:email_list' %}"><i
                    class="bi bi-envelope-plus"></i>
                Mensagens</a>
        </li>
        {% if config.ACCOUNT_ENABLE_INVITATION %}
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'emailtemplate:emailtemplate_list' %}"><i
                    class="bi bi-file-text"></i>
                Modelos</a>
        </li>
        {% endif %}
    </ul>
</li>
{% endif %}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownHelp" role="button"
        data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-cash-coin"></i> Produtos
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownHelp">
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'products:category_list' %}">
                <i class="bi bi-bag"></i> Categorias
            </a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'products:product_list' %}">
                <i class="bi bi-bag"></i> Produtos
            </a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'products:category_document_list' %}">
                <i class="bi bi-bag"></i> Documentos das categorias
            </a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'products:product_purchase_list' %}">
                <i class="bi bi-wallet"></i> Contratados
            </a>
        </li>
    </ul>
</li>


<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownHelp" role="button"
        data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-cash-coin"></i> Investimentos
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownHelp">
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'investment:applicationmodel_list' %}">
                <i class="bi bi-wallet2"></i> Modelos de aplicação
            </a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'investment:application_list' %}">
                <i class="bi bi-wallet2"></i> Aplicações
            </a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'investment:applicationaccount_list' %}">
                <i class="bi bi-wallet2"></i> Contas dos clientes
            </a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'investment:moneytransfer_list' %}">
                <i class="bi bi-arrow-left-right"></i> Solicitações de transferência
            </a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'investment:accop_schedule_list' %}">
                <i class="bi bi-clock"></i> Agendamentos
            </a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'investment:applicationop_list' %}">
                <i class="bi bi-file-spreadsheet"></i> Extratos
            </a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'investment:pool_account:income_operation_list' %}">
                <i class="bi bi-file-spreadsheet"></i> Rendimentos
            </a>
        </li>
    </ul>
</li>

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownHelp" role="button"
        data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-cash-coin"></i> Perfís
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownHelp">
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'products:profile_product_list' %}"><i
                    class="bi bi-coin"></i> Perfís</a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'investorprofile:profile_test_list' %}"><i
                    class="bi bi-clipboard"></i>
                Testes de perfil</a>
        </li>
    </ul>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownHelp" role="button"
        data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-file-text"></i> Contratos
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownHelp">
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'core:acceptance_term_list' %}"><i
                    class="bi bi-file-text"></i> Termos de aceite</a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'products:agreement_list' %}"><i
                    class="bi bi-file-text"></i> Produtos</a>
        </li>
    </ul>
</li>

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownHelp" role="button"
        data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-gear"></i> Site
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownHelp">
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'core:start_page_list' %}"><i
                    class="bi bi-file-code"></i> Página inicial</a>
        </li>
        <li><hr class="dropdown-divider"></li>        
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'core:faq_config_list' %}"><i
                    class="bi bi-question-circle-fill"></i> Páginas de ajuda</a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'core:faq_list' %}"><i
                    class="bi bi-file-text"></i> Questões frequentes</a>
        </li>
    </ul>
</li>

{% if request.user.is_staff %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownHelp" role="button"
        data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-gear"></i> Configurações
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownHelp">
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'core:company_list' %}"><i class="bi bi-building"></i>
                Empresa</a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="/admin/constance/config/"><i class="bi bi-server"></i>
                Adminitrativo</a>
        </li>
        <li>
            <a class="page-menu-link dropdown-item btn" href="{% url 'accounts:api_access_list' %}"><i
                    class="bi bi-gear"></i> Acesso à Api</a>
        </li>
    </ul>
</li>
{% endif %}

{% endblock%}

{% block user_profile %}
{% if request.user.is_authenticated %}
<li>
    <a class="page-menu-link dropdown-item" href="{% url 'core:admin_update' request.user.pk %}">
        <i class="bi bi-person-fill"></i> Perfil
    </a>
</li>
{% endif %}
{% endblock%}